server:
  servlet:
    context-path: /    encoding:      charset: utf-8
      enabled: true  port: 80

spring:  datasource:    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:    database-platform: org.hibernate.dialect.H2Dialect # 방언 설정
    hibernate:      ddl-auto: update # create: 서버 실행시마다 테이블 새로 생성 / update: 서버 실행시 이미 존재하면 생성x
    show-sql: true
    open-in-view: true

  jackson:    serialization:
      fail-on-empty-beans: false      